spring:
  application:
    name: msclientes
  datasource:
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://cursoms-eureka-user:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
